TARGET = probstatement_47_final


all:
	latex probstatement_47_final.tex
	dvips -R -Poutline -t letter probstatement_47_final.dvi -o probstatement_47_final.ps
	ps2pdf probstatement_47_final.ps
	rm probstatement_47_final.aux
	rm probstatement_47_final.dvi
	rm probstatement_47_final.log
	rm probstatement_47_final.ps
	rm probstatement_47_final.out